# permissions for end users to view apiwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiweb-viewer-role
rules:
- apiGroups:
  - hyperledger.example.org
  resources:
  - apiwebs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperledger.example.org
  resources:
  - apiwebs/status
  verbs:
  - get
