# permissions for end users to edit apiwebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiweb-editor-role
rules:
- apiGroups:
  - hyperledger.example.org
  resources:
  - apiwebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperledger.example.org
  resources:
  - apiwebs/status
  verbs:
  - get
