# permissions for end users to view certificateauthorities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateauthority-viewer-role
rules:
- apiGroups:
  - hyperledger.example.org
  resources:
  - certificateauthorities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperledger.example.org
  resources:
  - certificateauthorities/status
  verbs:
  - get
