# permissions for end users to edit certificateauthorities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateauthority-editor-role
rules:
- apiGroups:
  - hyperledger.example.org
  resources:
  - certificateauthorities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperledger.example.org
  resources:
  - certificateauthorities/status
  verbs:
  - get
